networks:
  tesselite-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 162.19.0.0/24

volumes:
  data:
  bin:

services:
  # reverse proxy
  lb:
    hostname: dev.user0.tesselite.tech
    extends:
      service: .lb
      file: template.yml
    image: lscr.io/linuxserver/swag:latest
    container_name: lb
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=env1.mlops.tesselite.dev
      - VALIDATION=http
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - EMAIL=marcel.ndeffo@gmail.com #optional
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
    volumes:
      - /home/contact/tls:/config
    ports:
      - 443:443
      - 80:80 #optional
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.5
    extra_hosts:
      - "admin:162.19.0.3"
      - "dev:162.19.0.2"

  dev:
    hostname: dev.user0.tesselite.tech
    container_name: dev
    image: marcelndeffo/tesselite:pythondev
    restart: always
    user: tesselite
    command:
      - jupyter
      - lab
      - "--port"
      - "8001"
      - "--ip"
      - "162.19.0.2"
      - "--token"
      - "tesselite"
      - "--allow_password_change"
      - "False"
    volumes:
      - data:/home/tesselite
      - bin:/usr/bin:ro
    ports:
      - "8001:8001"
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.2
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: "1500MB"
    logging:
      options:
        max-size: "10m"
        max-file: "50"

  admin:
    hostname: dev.user0.tesselite.tech
    container_name: admin
    image: marcelndeffo/tesselite:pythondev
    restart: always
    user: root
    command:
      - ttyd
      - "-p"
      - "8002"
      - "-c"
      - "root:tesselite"
      - "-b"
      - "/admin"
      - bash
    volumes:
      - data:/home/tesselite
      - bin:/usr/bin
    ports:
      - "8002:8002"
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.3
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "500MB"
    logging:
      options:
        max-size: "10m"
        max-file: "50"