networks:
  tesselite-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 162.19.0.0/24

volumes:
  data:
  bin:

services:
  # reverse proxy
  lb:
    hostname: dev.user0.tesselite.tech
    extends:
      service: .lb
      file: template.yml
    image: lscr.io/linuxserver/swag:latest
    container_name: lb
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=dev.user0.tesselite.tech
      - VALIDATION=http
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - EMAIL=marcel.ndeffo@gmail.com #optional
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
    volumes:
      - /home/contact/tls:/config
      - "../conf/nginx/dev-tls.nginx:/etc/nginx/site-confs/default.conf:ro"
    ports:
      - 443:443
      - 80:80
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.5
    extra_hosts:
      - "admin:162.19.0.3"
      - "dev:162.19.0.2"

  dev:
    extends:
      service: .dev
      file: template.yml
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.2

  admin:
    extends:
      service: .admin
      file: template.yml
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.3