networks:
  tesselite-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 162.19.0.0/24

volumes:
  data:
  bin:

services:
  # reverse proxy
  lb:
    hostname: dev.user0.tesselite.tech
    extends:
      service: .lb
      file: template.yml
    volumes:
      - "../conf/nginx/dev.nginx:/config/nginx/site-confs/dev.conf:ro"
      - "../conf/nginx/base.nginx:/etc/nginx/nginx.conf:ro"
    ports:
      - "80:80"
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.5
    extra_hosts:
      - "admin:162.19.0.3"
      - "dev:162.19.0.2"
    healthcheck:
      test: curl dev.user0.tesselite.tech|| exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  dev:
    extends:
      service: .dev
      file: template.yml
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.2

  admin:
    extends:
      service: .admin
      file: template.yml
    networks:
      tesselite-dev:
        ipv4_address: 162.19.0.3