name: build docker(s)

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/docker.yml
      - src/**
      - .build/mlflow/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { svc: "mlflow",  tag: "mlflow" }
          - { svc: "nfs",  tag: "nfs" }
          - { svc: "mlflow-auth0",  tag: "mlflow-auth0" }
          - { svc: "mlflow-api",  tag: "mlflow-api" }
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build Docker
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:.build/${{ matrix.svc }}"
        push: true
        tags: marcelndeffo/tools:${{ matrix.tag }}
